runtime: python27
api_version: 1
threadsafe: true


# [START handlers]
handlers:
- url: /static/adminlte
  static_files: ./flask_adminlte/static/(.*)/(.*)/(.*)/(.*)
  upload: ./flask_adminlte/static//(.*)/(.*)/(.*)/(.*)

- url: /static
  static_files: ./static/(.*)/(.*)/(.*)/(.*)
  upload: ./static/(.*)/(.*)/(.*)/(.*)

- url: /.*
  script: main.app

# [END handlers]
